# Generated by Django 5.2.1 on 2025-05-12 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=200)),
                ('card_number', models.BigIntegerField()),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('reciever_no', models.BigIntegerField()),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.account2')),
            ],
        ),
    ]
